name: "Create VyOS OCI image"

on:
  pull_request:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  VYOS_BUILD_DOCKER_IMAGE: vyos-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set VyOS version
        run: echo "VYOS_VERSION=$(cat vyos-version)" >> $GITHUB_ENV

      - name: Checkout vyos-build
        uses: actions/checkout@v3
        with:
          repository: vyos/vyos-build
          ref: ${{ env.VYOS_VERSION }}
          path: build

      - name: Checkout vyos-vm-images
        uses: actions/checkout@v3
        with:
          repository: vyos/vyos-vm-images
          path: vm-images

      - name: Gather Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=${{ env.VYOS_VERSION }}
      
      - name: Log in to the Container registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: build/docker
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Build ISO
      #   run: scripts/build_iso.sh